#!/bin/bash -eux
if ! git diff --cached --quiet --diff-filter=ACM -- simulator; then
  (
    cd simulator
    cargo check -q
    cargo clippy -q -- -Dwarnings
    cargo check -q --benches
    cargo build -q --target wasm32-unknown-unknown --no-default-features --features js
    cargo test -q
  )
fi

for PKG in frontend/app frontend/simulation_worker frontend/analyzer_worker; do
  if ! git diff --cached --quiet --diff-filter=ACM -- $PKG; then
    (
      cd $PKG
      cargo check -q --target wasm32-unknown-unknown
      cargo clippy -q --target wasm32-unknown-unknown -- -Dwarnings
      cargo build -q --target wasm32-unknown-unknown
    )
  fi
done

for PKG in tools services/compiler services/telemetry services/leaderboard; do
  if ! git diff --cached --quiet --diff-filter=ACM -- $PKG; then
    (
      cd $PKG
      cargo check -q
      cargo clippy -q -- -Dwarnings
      cargo build -q
    )
  fi
done
